# Generated by Django 4.1.1 on 2022-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services", name="desc", field=models.TextField(null=True),
        ),
    ]
