# Generated by Django 4.1.1 on 2022-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_services_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="desc",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
