# Generated by Django 4.1.1 on 2022-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_alter_services_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="listView",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="topView",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="topViewIcon",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
