# Generated by Django 4.1.1 on 2022-09-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_services_listview_services_topview_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="desc",),
        migrations.RemoveField(model_name="services", name="topViewIcon",),
    ]
